### ISSUE TITLE
Problem with saving the config file

### ISSUE THREAD

**Issue by jefflima1** [dodabyte/DodaLock#2] opened 2024-02-15 16:42 UTC
Hello, I configured the plugin, and it works as expected, but the config file does not save the settings, I edit it, whenever I restart the server the settings remain default, making it impossible to define another url for the resourcepack, or even deactivate it to use locally.

**Comment by dodabyte** [comment] 2024-02-16 04:07
> Hello, I configured the plugin, and it works as expected, but the config file does not save the settings, I edit it, whenever I restart the server the settings remain default, making it impossible to define another url for the resourcepack, or even deactivate it to use locally.

Hello, let me clarify, how do you save the configuration file? Do you edit it with the server turned off, and then turn it on, or do you edit it with the server turned on and write the /reload command?

The fact is that I have now checked the saving of the configuration file with the server turned off. After turning on the server, all my settings were saved, they were not restored by default.

Therefore, I would like to know from you in more detail how do you save the configuration file?

**Comment by jefflima1** [comment] 2024-02-16 08:43
Hello, I tried with the server turned on, and also with the server turned off, it doesn't accept it, whenever it starts or /reloads the config file returns to the default

**Comment by dodabyte** [comment] 2024-02-16 09:11
> Hello, I tried with the server turned on, and also with the server turned off, it doesn't accept it, whenever it starts or /reloads the config file returns to the default

Could you record a video with this problem and send it here?

At the moment, all my tests are being tested and there shouldn't be such a problem.

P.S. I have now checked the plugin on another device. Everything should work correctly.

**Comment by dodabyte** [comment] 2024-02-21 05:33
Since you don't get in touch and this kind of problem doesn't actually occur, can I close the issue?

**Comment by jefflima1** [comment] 2024-03-03 17:18
Hi, sorry... I can't save, but the problem is simple, saving the file with the server turned off, and putting my own LINK in dropbox to download the texture, as soon as the server starts, the download doesn't happen , when I go to check the file, it is set to the old link you provided, so I turn it off, and set the resourcepack to "false" so that it doesn't do any download, and even so when I turn it on again, a download is requested, which in this case it is to your old link, completely ignoring the "false" defined in the configuration file

**Comment by dodabyte** [comment] 2024-03-04 05:40
> Hi, sorry... I can't save, but the problem is simple, saving the file with the server turned off, and putting my own LINK in dropbox to download the texture, as soon as the server starts, the download doesn't happen , when I go to check the file, it is set to the old link you provided, so I turn it off, and set the resourcepack to "false" so that it doesn't do any download, and even so when I turn it on again, a download is requested, which in this case it is to your old link, completely ignoring the "false" defined in the configuration file

Hello. You can record a video with this problem and send it to me here? 

I tested the functionality of changing the configuration file many times and on different devices, but everything worked correctly.

**Comment by dodabyte** [comment] 2024-05-21 06:43
Since I did not wait for another response from you and could not reproduce this error according to your description, I consider this issue closed.

**Closed as completed by dodabyte** 2024-05-21 06:43 UTC
